const https = require('https');

module.exports = {
    name: 'ai',
    aliases: ['gpt', 'chatgpt', 'ask', 'gemini', 'bot'],
    category: 'ai',
    description: 'Auto-Adapting Google Gemini AI',
    usage: '.ai <question>',
    
    async execute(sock, msg, args, extra) {
        try {
            // 🚀 Aapki 100% working API key!
            const GEMINI_API_KEY = "AQ.Ab8RN6L8GOPoQLsPSfTspjW5HuY-C0tzQ-EV9vHMafqhhnTorg"; 

            if (!args[0]) {
                let errText = `❖ ───── ✦ 𝐄𝐑𝐑𝐎𝐑 ✦ ───── ❖\n\n`;
                errText += `❌ *Question Missing*\n`;
                errText += `💡 Please ask me anything.\n`;
                errText += `✦ *Example:* \`.ai Create a python loop script.\`\n`;
                errText += `╰━━━━━━━━━━━━━━━━━━┈⊷`;
                return extra.reply(errText);
            }

            const prompt = args.join(' ');
            if (extra.react) await extra.react('⏳');

            const requestBody = JSON.stringify({
                contents: [{ parts: [{ text: prompt }] }]
            });

            // 🧠 ARRAY OF MODELS: Agar ek fail hua, toh bot automatically dusra try karega!
            const modelsToTry = [
                'gemini-1.5-flash-latest', 
                'gemini-1.5-flash',
                'gemini-1.0-pro', 
                'gemini-pro'
            ];

            const fetchFromGoogle = (modelName) => {
                return new Promise((resolve, reject) => {
                    const options = {
                        hostname: 'generativelanguage.googleapis.com',
                        // 🛠️ Shifted back to v1beta for maximum model support, using URL key auth
                        path: `/v1beta/models/${modelName}:generateContent?key=${GEMINI_API_KEY}`,
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json',
                            'Content-Length': Buffer.byteLength(requestBody),
                            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)' 
                        },
                        timeout: 20000 
                    };

                    const req = https.request(options, (res) => {
                        let data = '';
                        res.on('data', chunk => data += chunk);
                        
                        res.on('end', () => {
                            try {
                                const json = JSON.parse(data);
                                
                                if (json.error) {
                                    reject(new Error(json.error.message));
                                    return;
                                }

                                if (json.candidates && json.candidates[0].content.parts[0].text) {
                                    resolve(json.candidates[0].content.parts[0].text.trim());
                                } else {
                                    reject(new Error("Invalid format received."));
                                }
                            } catch (e) {
                                reject(e);
                            }
                        });
                    });

                    req.on('error', reject);
                    req.on('timeout', () => {
                        req.destroy();
                        reject(new Error("Timeout"));
                    });

                    req.write(requestBody);
                    req.end();
                });
            };

            let finalAnswer = null;
            let lastError = "";

            // ⚙️ THE MAGIC LOOP: Testing models one by one silently
            for (let i = 0; i < modelsToTry.length; i++) {
                try {
                    console.log(`[AI ENGINE] Trying model: ${modelsToTry[i]}...`);
                    finalAnswer = await fetchFromGoogle(modelsToTry[i]);
                    
                    console.log(`[AI ENGINE] Success! Answer generated by ${modelsToTry[i]}`);
                    break; // Jaise hi answer milega, loop ruk jayega!
                } catch (err) {
                    console.log(`[AI ENGINE] Model ${modelsToTry[i]} failed: ${err.message}. Shifting to next...`);
                    lastError = err.message;
                    continue; // Pura crash hone ke bajaye next model try karo
                }
            }

            // 🚀 Final Result Delivery
            if (finalAnswer) {
                if (extra.react) await extra.react('✅');
                await extra.reply(finalAnswer);
            } else {
                // Agar chahro (4) models fail ho jayen (jo ke namumkin hai)
                if (extra.react) await extra.react('❌');
                await extra.reply(`❌ *Google AI Error:* All fallback models failed.\n💡 Last Error: ${lastError}`);
            }

        } catch (error) {
            console.error('\x1b[31m[CRITICAL ERROR]\x1b[0m', error);
            if (extra.react) await extra.react('❌');
            await extra.reply('❌ Bot system crashed while connecting to AI.');
        }
    }
};
